#define P_BOARD_OUTER_WRAAPER_REGEX @"var customboards_disp = new Array[\\s\\S]*document.write"
#define P_BOARD_SINGLE_BOARD_WRAPPER_REGEX @"</a>-->[\\s\\S]*?(?=</td></tr></table></TD>)"
#define P_BOARD_NAME_REGEX @"(?<=<font color=#000066>).*?(?=</font>)"
#define P_BOARD_ID_REGEX @"(?<=<a href=\"list.asp\\?boardid=)[0-9]+(?=\">)"
#define P_BOARD_INTRO_REGEX @"(?<=<img src=pic/Forum_readme.gif align=middle>).*?(?=</FONT></TD></TR>)"
#define P_BOARD_LAST_REPLY_TOPIC_ID_REGEX @"(?<=&ID=)\\d*?(?=\">)"
#define P_BOARD_LAST_REPLY_TOPIC_NAME_REGEX @"(?<=ID=\\d{0,10}\">)[\\s\\S]*(?=</a><BR>作者)"
#define P_BOARD_LAST_REPLY_AUTHOR_REGEX @"(?<=blank>).*?(?=</a><BR>)"
#define P_BOARD_LAST_REPLY_TIME_REGEX @"(?<=bottom\">).*?(?=</a>)"
#define P_BOARD_LAST_REPLY_LINK_REGEX @"(?<=日期：<a href=\").*?(?=#bottom\")"
#define P_BOARD_BOARD_MASTER_REGEX @"版主：.*?</a>(?=&nbsp;</TD>)"
#define P_BOARD_POST_NUMBER_TODAY @"(?<=<font color=#FF0000>).*?(?=</font></td>)"