#define P_BOARD_OUTER_WRAAPER_REGEX @"var customboards_disp = new Array[\\s\\S]*document.write"
#define P_BOARD_SINGLE_BOARD_WRAPPER_REGEX @"</a>-->[\\s\\S]*?(?=</td></tr></table></TD>)"
#define P_BOARD_NAME_REGEX @"(?<=<font color=#000066>).*?(?=</font>)"
#define P_BOARD_ID_REGEX @"(?<=<a href=\"list.asp\\?boardid=)[0-9]+(?=\">)"
#define P_BOARD_INTRO_REGEX @"(?<=<img src=pic/Forum_readme.gif align=middle>).*?(?=</FONT></TD></TR>)"
#define P_BOARD_LAST_REPLY_TOPIC_ID_REGEX @"(?<=&ID=)\\d*?(?=\">)"
#define P_BOARD_LAST_REPLY_TOPIC_NAME_REGEX @"(?<=ID=\\d{0,10}\">)[\\s\\S]*(?=</a><BR>作者)"
#define P_BOARD_LAST_REPLY_AUTHOR_REGEX @"(?<=blank>).*?(?=</a><BR>)"
#define P_BOARD_LAST_REPLY_TIME_REGEX @"(?<=bottom\">).*?(?=</a>)"
#define P_BOARD_LAST_REPLY_LINK_REGEX @"(?<=日期：<a href=\").*?(?=#bottom\")"
#define P_BOARD_BOARD_MASTER_REGEX @"版主：.*?</a>(?=&nbsp;</TD>)"
#define P_BOARD_POST_NUMBER_TODAY @"(?<=<font color=#FF0000>).*?(?=</font></td>)"

#define HOT_TOPIC_WRAPPER @"&nbsp;<a href=\".*?(</td></tr><TR><TD align=middle|</td></tr><!--data)"
#define HOT_TOPIC_NAME_REGEX @"(?<=\\<font color=#000066>).*?(?=\\</font>)"
#define HOT_TOPIC_ID_REGEX @"(?<=&id=).*?(?=\" )"
#define HOT_TOPIC_BOARD_ID_REGEX @"(?<=boardid=)\\d{0,5}?(?=&id=)"
#define HOT_TOPIC_BOARD_NAME_WITH_AUTHOR_REGEX @"(?<=target=\"_blank\">).{0,30}?(?=</a></td><td height=20)"
#define HOT_TOPIC_POST_TIME_REGEX @"(?<=\">).{5,18}?(?=</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)"
#define HOT_TOPIC_CLICK_REGEX @"(?<=align=middle class=tablebody\\d>).*?(?=</td>)"

#define USER_PROFILE_AVATAR_REGEX @"(?<=&nbsp;\\<img src=).*?(?= )"
#define USER_PROFILE_GENERAL_PROFILE_REGEX @"用户头衔：.*?最后登录：.*?<br>"
#define USER_PROFILE_PERSON_PROFILE_REGEX @"性 别.*?主 页.*?</font>"
#define USER_PROFILE_BBS_MASTER_INFO_REGEX @"(?<=<font align=left>)论坛职务：</font><br>.*?(?=<td  class=tablebody1)"
#define USER_PROFILE_ONLINE_INFO_REGEX @"(?<=&nbsp;&nbsp;状态：).*?\\]"

#define POST_LIST_POST_TYPE_REGEX @"(?<=alt=).*?(?=></TD>)"
#define POST_LIST_POST_NAME_REGEX @"(?<=最后跟贴：\">).*?(?=</a>)"
#define POST_LIST_POST_ID_REGEX @"(?<=&ID=)\\d{1,10}?(?=&page=)"
#define POST_LIST_POST_BOARD_ID_REGEX @"(?<=dispbbs.asp\\?boardID=)\\d{1,10}?(?=&ID=)"
#define POST_LIST_POST_PAGE_NUMBER_REGEX @"(?<=<font color=#FF0000>).{1,6}?(?=</font></a>.?</b>\\])"
#define POST_LIST_POST_AUTHOR_NAME_REGEX @"(?<=target=\"_blank\">).{1,15}(?=</a>)|(?<=<td width=80 nowrap class=tablebody2>).{1,15}?(?=</td>)"
#define POST_LIST_REPLY_NUM_REGEX @"(?<=<td width=\\* nowrap class=tablebody1>).*?(?=</td>)"
#define POST_LIST_LAST_REPLY_TIME_REGEX @"(?<=#bottom\">).*?(?=</a>)"
#define POST_LIST_LAST_REPLY_AUTHOR_REGEX @"(?<=usr\":\").*?(?=\")"
#define POST_LIST_POST_ENTITY_REGEX @"(?<=<tr style=\"vertical-align: middle;\">).*?(?=;</script>)"